import { Component, OnInit } from '@angular/core';
import {
  ABOUT_EPIGRAPH1, ABOUT_EPIGRAPH2, ABOUT_EPIGRAPH3, ABOUT_EPIGRAPH_SIGNATURE, ABOUT_HEADER,
  PSYCHOLOGICAL_COMPATIBILITY_CAN_BE_MEASURED_DESCRIPTION, PSYCHOLOGICAL_COMPATIBILITY_CAN_BE_MEASURED_FOOTER,
  PSYCHOLOGICAL_COMPATIBILITY_CAN_BE_MEASURED_HEADER,
  PSYCHOLOGICAL_COMPATIBILITY_CAN_BE_MEASURED_LIST11, PSYCHOLOGICAL_COMPATIBILITY_CAN_BE_MEASURED_LIST12,
  PSYCHOLOGICAL_COMPATIBILITY_CAN_BE_MEASURED_LIST21, PSYCHOLOGICAL_COMPATIBILITY_CAN_BE_MEASURED_LIST22,
  PSYCHOLOGICAL_COMPATIBILITY_CAN_BE_MEASURED_LIST31, PSYCHOLOGICAL_COMPATIBILITY_CAN_BE_MEASURED_LIST32,
  PSYCHOLOGICAL_COMPATIBILITY_CAN_BE_MEASURED_LIST41, PSYCHOLOGICAL_COMPATIBILITY_CAN_BE_MEASURED_LIST42,
  PSYCHOLOGICAL_COMPATIBILITY_HEADER, PSYCHOLOGICAL_COMPATIBILITY_DESCRIPTION,
  PSYCHOLOGICAL_COMPATIBILITY_LIST1, PSYCHOLOGICAL_COMPATIBILITY_LIST2,
  PSYCHOLOGICAL_COMPATIBILITY_LIST3, PSYCHOLOGICAL_COMPATIBILITY_LIST4, PSYCHOLOGICAL_COMPATIBILITY_FOOTER,
  PSYCHOLOGICAL_INCOMPATIBILITY_HEADER,
  PSYCHOLOGICAL_INCOMPATIBILITY_DESCRIPTION

} from './about-project';

@Component({
  selector: 'app-psychological-compatibility-info',
  templateUrl: './psychological-compatibility-info.component.html',
  styleUrls: ['./psychological-compatibility-info.component.scss']
})
export class PsychologicalCompatibilityInfoComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
