import {DeactivationGuarded, DeactivationLoginRegistrationGuarded} from '../../guard/can-deactivate.guard';
import {SendingTokensService} from '../sending-tokens/sending-tokens.service';

export enum ComponentName {
  TOKEN_INTERCEPTOR = 'TOKEN-INTERCEPTOR',

  LOGIN = 'LOGIN',
  LOGIN_SERVICE = 'LOGIN-SERVICE',
  LOGOUT = 'LOGOUT',

  REGISTRATION = 'REGISTRATION',
  REGISTRATION_SERVICE = 'REGISTRATION-SERVICE',
  ANONIM_REGISTRATION = 'ANONIM-REGISTRATION',

  TEST_HOME_PAGE = 'TEST-HOME-PAGE',
  TEST_INFO_CARDS = 'TEST-INFO-CARDS',
  VALUE_COMPATIBILITY = 'VALUE-COMPATIBILITY',
  VALUE_COMPATIBILITY_PROFILE = 'VALUE-COMPATIBILITY-PROFILE',
  VALUE_COMPATIBILITY_TEST_INSTRUCTION = 'VALUE-COMPATIBILITY-TEST-INSTRUCTION',
  VALUE_COMPATIBILITY_SERVICE = 'VALUE-COMPATIBILITY-SERVICE',

  MATCH_HOME_PAGE = 'MATCH-HOME-PAGE',
  MATCH_VALUE_COMPATIBILITY = 'MATCH-VALUE-COMPATIBILITY',
  MATCH_VALUE_COMPATIBILITY_SERVICE = 'MATCH-VALUE-COMPATIBILITY-SERVICE',

  USER_ACCOUNT = 'USER-ACCOUNT',
  USER_ACCOUNT_SERVICE = 'USER-ACCOUNT-SERVICE',

  HEADER = 'HEADER',
  RETURN_TO_FRIEND_ACCOUNT = 'RETURN-TO-FRIEND-ACCOUNT',
  TEST_FRIEND = 'TEST-FRIEND',
  TEST_FRIEND_BUTTON = 'TEST-FRIEND-BUTTON',
  TEST_NOT_PASSED = 'TEST_NOT_PASSED',
  SENDING_TOKENS_SERVICE = 'SENDING-TOKENS-SERVICE',
  SENDING_TOKENS = 'SENDING-TOKENS',

  AUTH_GUARD = 'AUTH-GUARD',
  REGISTRATION_GUARD = 'REGISTRATION-GUARD',
  ANONIM_REGISTRATION_GUARD = 'ANONIM-REGISTRATION-GUARD',
  CAN_DEACTIVATE_GUARD = 'CAN-DEACTIVATE-GUARD',
  DEACTIVATION_GUARDER = 'DEACTIVATION-GUARDER',
  DEACTIVATION_LOGIN_REGISTRATION_GUARDER = 'DEACTIVATION-LOGIN-REGISTRATION-GUARDER',

}
